# tmux.conf - Tmux configuration

# Enable mouse support
set -g mouse on

# 256 Colors & TrueColor (24-bit RGB) Support inside Ghostty / Terminal
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ",xterm-ghostty:RGB"

# Enable focus events for applications that support them (like Vim)
set -g focus-events on

# copy to macOS clipboard automatically on mouse drag end inside tmux copy-mode
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
