#!/bin/bash

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins/
chunkc core::hotload 1
chunkc core::load tiling.so

chunkc set global_desktop_mode           bsp

chunkc set global_desktop_offset_top     0
chunkc set global_desktop_offset_bottom  0
chunkc set global_desktop_offset_left    0
chunkc set global_desktop_offset_right   0
chunkc set global_desktop_offset_gap     0 

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           0
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1


chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        12
chunkc set preselect_border_radius       0


chunkc set focused_border_color          0xff0f6288
chunkc set focused_border_width          8
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  1

chunkc tiling::rule --owner Finder --state float
chunkc tiling::rule --owner Spotify --state float
chunkc tiling::rule --owner MacPass --state float
chunkc tiling::rule --owner \"Soda Player\" --state float
chunkc tiling::rule --owner Signal --state float
chunkc tiling::rule --owner Tweetbot --state float
chunkc tiling::rule --owner \"Google Play Music Desktop Player\" --state float

